## Bank Statement - PDF

##### 20240525163216_BM_Soft_Transaction_Inquiry_01.pdf

In [13]:
from img2table.document import PDF
from img2table.ocr import DocTR
import pandas as pd

file = PDF("sample/pdf/20240525163216_BM_Soft_Transaction_Inquiry_01.pdf")

ocr = DocTR(kw={"pretrained": True})

tables = file.extract_tables(ocr=ocr, borderless_tables=True, min_confidence=50).copy()

c:\Users\Azer\miniconda3\envs\test_img2table\lib\site-packages\img2table\tables\processing\bordered_tables\cells\identification.py:17: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  .rename({col: f"{col}_" for col in df_h_lines.columns})
c:\Users\Azer\miniconda3\envs\test_img2table\lib\site-packages\img2table\tables\processing\bordered_tables\cells\deduplication.py:21: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  .rename({col: f"{col}_" for col in df_cells.columns})

In [14]:
tables.items()

dict_items([(0, [ExtractedTable(title=None, bbox=(78, 281, 1337, 643),shape=(6, 3)), ExtractedTable(title=None, bbox=(85, 710, 1881, 798),shape=(1, 5)), ExtractedTable(title=None, bbox=(83, 799, 1830, 2270),shape=(25, 7))]), (1, [ExtractedTable(title=TRANSACTION INQUIRY
Period
:
From
12 January 2021
To
22 January 2021
1440003022453 - ROSANA HAYATI
Account No
:
Currency
:
IDR
Branch
:
KCP Pasuruan, bbox=(85, 710, 1881, 800),shape=(1, 5)), ExtractedTable(title=None, bbox=(78, 846, 1830, 1369),shape=(3, 7))])])

In [15]:
result = pd.concat([tables[0].pop(2).df.fillna("")], ignore_index=True)
result

,0,1,2,3,4,5,6
0,12/01/2021 13.18.32,12/01/2021,KE MANDIRI PRIBADI,,0.00,"10,000,000.00","10,172,609.62"
1,,,MCM InhouseTrf DARI ROSANA,,,,
2,,,BIRO PERJALANAN WISATA,,,,
3,12/01/2021 13.23.00,12/01/2021,030302160140152705304940,,"2,500.00",0.00,"10,170,109.62"
4,,,INT-B(Bil Pmt) Telkom,,,,
5,12/01/2021 13.23.00,12/01/2021,0152705304940\n030302160140152705304940,,"352,000.00",0.00,"9,818,109.62"
6,,,INT-B(Bil Pmt) Telkom,,,,
7,12/01/2021 14.27.41,12/01/2021,0152705304940\nKE MANDIRI PRIBADI,,0.00,"10,000,000.00","19,818,109.62"
8,,,MCM InhouseTrf DARI ROSANA,,,,
9,12/01/2021 14.30.12,12/01/2021,BIRO PERJALANAN WISATA\nCHEF KULINER INDRAGI,,"10,000,000.00",0.00,"9,818,109.62"
10,,,MCM InhouseTrf KE TEGUH,,,,
11,14/01/2021 09.06.32,14/01/2021,BASUKI UTOMO\nBRT INA KHATAMAN BHU,,"850,000.00",0.00,"8,968,109.62"
12,14/01/2021 09.06.32,14/01/2021,MCM Outw CN MUTMAINAH\nClearing Fee BRT INA\nK...,BRT INA\nKHATAMAN BH,"2,900.00",0.00,"8,965,209.62"
13,15/01/2021 08.26.40,15/01/2021,Clearing Fee\nMENGGANTI ONGKOS KCA,,"25,000.00",0.00,"8,940,209.62"
14,15/01/2021 08.26.40,15/01/2021,MCM Outw CN ROBI HANGGARA\nClearing Fee MENGGA...,MENGGANTI\nONGKOS KC,"2,900.00",0.00,"8,937,309.62"
15,16/01/2021 12.48.21,16/01/2021,Clearing Fee\nBRT UPAH PAK PARNI,,"2,265,000.00",0.00,"6,672,309.62"
16,16/01/2021 12.48.22,16/01/2021,MCM InhouseTrf KE SUPARNI\nBRT UPAH PAK PARNI,,"825,000.00",0.00,"5,847,309.62"
17,16/01/2021 12.48.23,16/01/2021,MCM InhouseTrf KE SUPARNI\nBRT UPAH PAK PARNI,,"330,000.00",0.00,"5,517,309.62"
18,16/01/2021 12.48.24,16/01/2021,MCM InhouseTrf KE SUPARNI\nBRT UPAH PAK PARNI,,"330,000.00",0.00,"5,187,309.62"
19,18/01/2021 09.00.34,18/01/2021,MCM InhouseTrf KE SUPARNI\nMENGGANTI TIPS TEGAL,,"200,000.00",0.00,"4,987,309.62"
20,,,MCM Outw CN BPK MUHAMAD,,,,
21,18/01/2021 09.00.34,18/01/2021,SHOLEH\nClearing Fee MENGGANTI\nTIPS TEGA,MENGGANTI TIPS\nTEGA,"2,900.00",0.00,"4,984,409.62"
22,18/01/2021 09.00.35,18/01/2021,Clearing Fee\nMENGGANTI BBM PICKUP,,"200,000.00",0.00,"4,784,409.62"
23,18/01/2021 09.00.35,18/01/2021,MCM Outw CN ROBI HANGGARA\nClearing Fee MENGGANTI,MENGGANTI BBM,"2,900.00",0.00,"4,781,509.62"
24,,,BBM PICKU,PICKU,,,